### ISSUE TITLE
缺少pgrk.txt文件

### ISSUE THREAD

**Issue by miaozjs** [shijx12/KQAPro_Baselines#1]
KQAPro_Baselines-master/SRN/knowledge_graph.py, line 29, in load_pgrk_score
    with open(os.path.join(self.args.input_dir, 'pgrk.txt')) as f:

SRN/knowledge_graph.py中需要文件pgrk.txt，请问这个文件是什么，数据处理中没有生成这个文件

**Comment by ShulinCao** [comment]
这是图中各个节点pagerank的文件，已经上传
