### ISSUE TITLE
About special predicates

### ISSUE THREAD

**Issue by yhshu** [shijx12/KQAPro_Baselines#10]
Hi there,
special tokens such as 
```python
    PRED_INSTANCE = 'pred:instance_of'
    PRED_NAME = 'pred:name'

    PRED_VALUE = 'pred:value'  # link packed value node to its literal value
    PRED_UNIT = 'pred:unit'  # link packed value node to its unit

    PRED_YEAR = 'pred:year'  # link packed value node to its year value, which is an integer
    PRED_DATE = 'pred:date'  # link packed value node to its date value, which is a date

    PRED_FACT_H = 'pred:fact_h'  # link qualifier node to its head
    PRED_FACT_R = 'pred:fact_r'
    PRED_FACT_T = 'pred:fact_t'
```

It seems that these tokens are not supported by [official Wikidata query service](https://query.wikidata.org) . Is there any document explains about how these tokens work?

**Comment by ShulinCao** [comment]
They are used to build our SPARQL engine. To denote qualifiers, we create a virtual node for those literal and relational triples. For example, to denote the start time of (Kobe Bryant, spouse, Vanessa Laine Bryant), we create a node _BN which connects to the subject, the predicate, and the object with three special edges, and then add (_BN, start time, 2001) into the graph. Similarly, we use virtual node to represent the attribute value of number type, which has an extra unit. For example, to represent the height of Yao Ming, we need (Yao Ming, height, _BN), (_BN, value, 229), (_BN, unit, centimetre).

**Comment by yhshu** [comment]
Thanks for your reply.
