### ISSUE TITLE
bart large cant be trained cuz out of memory

### ISSUE THREAD

**Issue by 652994331** [shijx12/KQAPro_Baselines#13]
Hi, trying to revive the result of bart_program, it seems they used bart-large model. When i load barge large and trained, it failed cuz out of memory problem, tried to reduce the size of batch but no luck, could you please help, thank you

**Comment by ShulinCao** [comment]
We used bart-base model. Please refer to https://github.com/shijx12/KQAPro_Baselines/tree/master/Bart_Program#checkpoints

**Comment by 652994331** [comment]
thank you for the quick reply, i would try base model

**Comment by 652994331** [comment]
i usedbart-base from huggingface, it worked, thank you. Later, i found this issue, https://github.com/shijx12/KQAPro_Baselines/issues/5.  According to this issue,  it seems you are using a special pret-trained model which has 768 hidden size. However, the hidden size is 1024 from the code which generates this error below
<img width="567" alt="Screen Shot 2022-02-21 at 10 05 54 PM" src="https://user-images.githubusercontent.com/51428350/155072719-a4a46196-9686-415a-a183-5c2975d6de06.png">
i am a little confused now, can you show which pre-trained model should i use to get the result from paper. thank you

**Comment by 652994331** [comment]
@solved, u need to update transformer to the newest version
