### ISSUE TITLE
in KQAPro's 'kb.json' there is 'subClassOf' instead of 'instanceOf' for concepts

### ISSUE THREAD

**Issue by stellarkey** [shijx12/KQAPro_Baselines#19]
In the code: https://github.com/shijx12/KQAPro_Baselines/blob/master/utils/load_kb.py#L15

```
knowledge json format:
    'concepts':
    {
        'id':
        {
            'name': '',
            'instanceOf': ['<concept_id>'],
        }
    },
......
```

While in KQAPro's dataset:

```
{
    "concepts": {
        "Q7270": {
            "name": "republic",
            "subclassOf": [
                "Q7174"
            ]
        },
```

in the paper: ([KQA Pro](https://aclanthology.org/2022.acl-long.422.pdf))

![image](https://user-images.githubusercontent.com/38290992/175076625-1541fdad-36ca-45bb-ab6a-561bc1951801.png)

---

Using `subClassOf` might be more reasonable comparing to `instanceOf`?

**Comment by ShulinCao** [comment]
The newly updated version fixed this problem.
