### ISSUE TITLE
no module named V2_Bart_Program

### ISSUE THREAD

**Issue by cdhx** [shijx12/KQAPro_Baselines#3]
predicate.py in BART Program has line as follow

`from V2_Bart_Program.executor_rule import RuleExecutor`

however，this is no file named V2_Bart_Program

do you mean the excutor_rule.py in Bart_Program？or forget to update a new version of Bart_program?

thx

**Comment by cdhx** [comment]
plus，this `required=True` sames not necessary in predicate.py

`parser.add_argument('--model_name_or_path', required=True)`

**Comment by ShulinCao** [comment]
We mean the former. Thank you for your advice~
