### ISSUE TITLE
What do <b> and <c> mean in Program?

### ISSUE THREAD

**Issue by yhshu** [shijx12/KQAPro_Baselines#9]
I assume that `<b>` splits functions, and `<c>` splits arguments of functions, is it true?

Thanks for your reply.

**Comment by ShulinCao** [comment]
Exactly~

**Comment by yhshu** [comment]
I haven't actually experimented to the stage of generating results, so there's a question.
The transformer tokenizer, i.e., BART tokenizer here, generally separates symbols like `<` `>` from words. 
Is there any post-process for seq2seq results to eliminate the side effect, or deal with the possible ill-format SPARQL or Program?

**Comment by ShulinCao** [comment]
For SPARQL，there is  post-process as shown in https://github.com/shijx12/KQAPro_Baselines/blob/2c5049900ba11947daf32cffcdfbdb4e985f1108/Bart_SPARQL/predict.py#L90.
